Implement the download_file widget action
nordeck/matrix-widget-toolkit pull request #759
Opened 2024-08-26 09:08 UTC by weeman1337

Needs https://github.com/matrix-org/matrix-react-sdk/pull/12927

**:heavy_check_mark: Checklist**

- [x] A changeset describing the change and affected packages ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#changelog-and-versioning)).
- [x] Added or updated documentation.
- [ ] Tests for new functionality and regression tests for bug fixes.
- [ ] Screenshots or videos attached (for UI changes).
- [x] All your commits have a `Signed-off-by` line in the message ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#dco)).

2024-08-28 10:27 UTC, HarHarLinks requested changes
something is wrong, the upload happens 3 times every time i try it:
![image](https://github.com/user-attachments/assets/a4f1abea-a241-45b9-8977-78cdc141f984)

2024-08-28 11:18 UTC, HarHarLinks submitted a review, later dismissed

2024-08-28 11:57 UTC, HarHarLinks commented
test setup: https://github.com/matrix-org/matrix-widget-api/pull/99#issuecomment-2314962447

2024-08-30 15:16 UTC, HarHarLinks commented
matrix-widget-api was merged and released as 0.9.0, matrix-react-sdk was merged and is slated for the next element-web release cycle (RC on 2024-09-03 and release on 2024-09-10).

2024-09-02 11:14 UTC, HarHarLinks commented
one missing part appears
```
diff --git a/example-widget-mui/src/ImagePage/ImagePage.test.tsx b/example-widget-mui/src/ImagePage/ImagePage.test.tsx
index 69233d9..9842b7a 100644
--- a/example-widget-mui/src/ImagePage/ImagePage.test.tsx
+++ b/example-widget-mui/src/ImagePage/ImagePage.test.tsx
@@ -95,6 +95,7 @@ describe('<ImagePage>', () => {
         ROOM_EVENT_UPLOADED_IMAGE,
       ),
       WidgetApiFromWidgetAction.MSC4039UploadFileAction,
+      WidgetApiFromWidgetAction.MSC4039DownloadFileAction,
       WidgetApiFromWidgetAction.MSC4039GetMediaConfigAction,
     ]);
 ```

2024-09-03 22:26 UTC, mgcm approved these changes
🚀

2024-09-04 15:08 UTC, merged