Less hacky way of having alternate listen directives
nordeck/matrix-widget-toolkit pull request #865
Opened 2024-11-22 17:02 UTC by mgcm

**:heavy_check_mark: Checklist**

- [X] A changeset describing the change and affected packages ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#changelog-and-versioning)).
- [X] Added or updated documentation.
- [ ] Tests for new functionality and regression tests for bug fixes.
- [ ] Screenshots or videos attached (for UI changes).
- [X] All your commits have a `Signed-off-by` line in the message ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#dco)).

2024-11-27 12:00 UTC, HarHarLinks requested changes
test pending, but it looks good overall, just some docs cleanup.

let's discuss which one to take provided my testing is successful just now.

2024-11-27 12:00 UTC, HarHarLinks commented on containers/widget-server/README.md
> +- ALlows for IPv4-only deployments.
```suggestion
- Allows for IPv4-only deployments.
```

2024-11-27 12:00 UTC, HarHarLinks commented on containers/widget-server/Dockerfile
> +# on your deployments to support different configs (eg. IPv4-omly).
```suggestion
# on your deployments to support different configs (e.g. IPv4-only).
```

2024-11-27 12:00 UTC, HarHarLinks commented on containers/widget-server/README.md
> +Simply replace the `/etc/nginx/conf.d/custom/content-security-policy.conf` file in when building your container image or in the deployment.
Can we also fix this sentence: in where?

2024-11-27 12:00 UTC, HarHarLinks commented on containers/widget-server/files/default.conf
> +  # include additional headers that are located in separate files (CSP, listen, ...)
not entirely accurate since the next line now also includes the listen.conf

2024-11-27 12:00 UTC, HarHarLinks commented on containers/widget-server/README.md
We should document that you can mount even more files into conf.d/custom and they will be included in the `server` block. Any security implications by allowing this? You could probably mount anything you want anyway, right?

This feature should then also make it into any helm charts and similar consumers of this image we maintain.

2024-11-27 12:00 UTC, HarHarLinks commented on containers/widget-server/README.md
> +We provide an IPv4-only example in `files/listen.ipv4.conf` file.
Trying to tweak the wording here
```suggestion
If you need to change this, for example to set up an IPv4-only deployment, you can replace the
`/etc/nginx/conf.d/custom/listen.conf` file within the container at build time or by mounting an alternative configuration file.

We provide an IPv4-only example in the `files/listen.ipv4.conf` file.
```

2024-11-27 12:36 UTC, HarHarLinks commented
For the results from testing, see https://github.com/nordeck/matrix-widget-toolkit/pull/860#issuecomment-2503742213

2024-11-27 13:43 UTC, mgcm commented on containers/widget-server/README.md
Added a mention to the README as suggested.

2024-12-06 10:17 UTC, HarHarLinks commented on containers/widget-server/README.md
is now NEO-1092

2024-12-06 10:17 UTC, HarHarLinks approved these changes

2024-12-06 10:18 UTC, merged